### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by henry-hz**
Dear Sasha, let me suggest to update the dependencies, as our projects also use the same dependencies, we are having conflicts.

### CODE REVIEW

**Comment by sashaafm** [comment]
Hi @henry-hz thank you for the PR. Have you tested GCloudex with those dependencies? I believe I had tried with those but some of the inner deps were broken because they needed older versions. I'll take a look and test it this week :+1: 

Also, are you using GCloudex in any of your projects? :100:

**Comment by henry-hz** [comment]
Hi Sacha, in fact, because of broken dependencies, we made our own lib, but a very simple one, we would prefer to migrate to yours lib :)

**Comment by sashaafm** [comment]
@henry-hz I tested locally and everything seems fine. I merged your PR. Glad you enjoy this library and that you find it useful in your projects.

:+1: Thank you :+1:

**Comment by henry-hz** [comment]
@sashaafm Thanks!

**Pull request merged**
